title: Science Fiction Farms
# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/local/bg/space.jpg") fixed
resources:
  - url: /local/send-json-to-topic-card.js
    type: module
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # View tab title.
  - title: H.A.L
    # Optional unique id for direct access /lovelace/${id}
    id: hal
    # Optional background (overwrites the global background).
    #background: center / cover no-repeat url("/local/bg/space.jpg") fixed
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
      - type: "custom:send-json-to-topic-card"
        title: Configure H.A.L.s
      - type: entities
        # Title of the entities card
        title: H.A.L. settings
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: input_text.id
            name: H.A.L. ID
          - entity: input_text.ssid
            name: Wireless Network Name
          - entity: input_text.wifi_password
            name: Wireless Network Password
          - entity: input_text.mqtt_host
            name: MQTT Host Name
          - entity: script.build_esp
            name: Build H.A.L.
        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: light.bed_light

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    background: radial-gradient(crimson, skyblue)
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.

        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.paulus
          - device_tracker.anne_there
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home


